import com.example.SimpleSwaggerToJavaTask

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the library convention plugin for shared build configuration between library and application projects.
    id("pingfed.automation.java-library-conventions")


}

dependencies {

        implementation("io.swagger:swagger-codegen:2.4.28")

}



tasks.register<SimpleSwaggerToJavaTask>("swagger2java") {
    group="codegen";

    doFirst {
       /** println("configured sourceSets from ---");
        val genJavaSrcFile:File= File(target.get().asFile, "java");
        val genSourceDir:String = genJavaSrcFile.absolutePath;
       java {

            val mainJavaSourceSet: SourceDirectorySet = sourceSets.getByName("main").java
            mainJavaSourceSet.srcDir(genSourceDir);
            println(mainJavaSourceSet.srcDirs)
        }*/
    }
}
