import com.example.SimpleSwaggerToJavaTask
import org.gradle.kotlin.dsl.dependencies

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the library convention plugin for shared build configuration between library and application projects.
    id("pingfed.automation.java-library-conventions")


}

dependencies {

        implementation("io.swagger:swagger-codegen:2.4.28")

}

tasks.register<SimpleSwaggerToJavaTask>("swagger2java") {
    group="classes";
    doLast {
        println("2java");
    }
}
